# Generated by Django 3.2.15 on 2022-09-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo2app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2017-12-14'),
            preserve_default=False,
        ),
    ]
